"""normalizacion tablas paz y salvo y firmas

Revision ID: 397a33327c66
Revises: 893592e6ba36
Create Date: 2026-05-26 18:03:45.522294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397a33327c66'
down_revision: Union[str, None] = '893592e6ba36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credenciales_login',
    sa.Column('id_credencial', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_credencial')
    )
    op.create_index(op.f('ix_credenciales_login_id_credencial'), 'credenciales_login', ['id_credencial'], unique=False)
    op.create_table('tipo_firma',
    sa.Column('id_tipo_firma', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_firma'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipo_firma_id_tipo_firma'), 'tipo_firma', ['id_tipo_firma'], unique=False)
    op.create_table('responsable_firma',
    sa.Column('id_responsable', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('ruta_firma', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_responsable')
    )
    op.create_index(op.f('ix_responsable_firma_id_responsable'), 'responsable_firma', ['id_responsable'], unique=False)
    op.create_table('detalle_firma_paz_y_salvo',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_firma', sa.Integer(), nullable=False),
    sa.Column('id_tipo_firma', sa.Integer(), nullable=False),
    sa.Column('id_usuario_firmante', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('fecha_firma', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_firma'], ['firmas_paz_y_salvo.id_firma'], ),
    sa.ForeignKeyConstraint(['id_tipo_firma'], ['tipo_firma.id_tipo_firma'], ),
    sa.ForeignKeyConstraint(['id_usuario_firmante'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_detalle_firma_paz_y_salvo_id_detalle'), 'detalle_firma_paz_y_salvo', ['id_detalle'], unique=False)
    op.drop_index('ix_dir_firmas_id_dir_firma', table_name='dir_firmas')
    op.drop_table('dir_firmas')
    op.alter_column('firmas_paz_y_salvo', 'id_estudiante',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('firmas_paz_y_salvo', 'id_periodo',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('firmas_paz_y_salvo', 'inventario')
    op.drop_column('firmas_paz_y_salvo', 'prueba')
    op.drop_column('firmas_paz_y_salvo', 'tesoreria')
    op.drop_column('firmas_paz_y_salvo', 'rectoria')
    op.drop_column('firmas_paz_y_salvo', 'uniforme')
    op.drop_column('firmas_paz_y_salvo', 'pupitre')
    op.drop_column('firmas_paz_y_salvo', 'banda')
    op.add_column('inventario_libro', sa.Column('edicion', sa.String(length=50), nullable=True))
    op.alter_column('inventario_libro', 'disponible',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventario_libro', 'disponible',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('inventario_libro', 'edicion')
    op.add_column('firmas_paz_y_salvo', sa.Column('banda', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('firmas_paz_y_salvo', sa.Column('pupitre', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('firmas_paz_y_salvo', sa.Column('uniforme', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('firmas_paz_y_salvo', sa.Column('rectoria', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('firmas_paz_y_salvo', sa.Column('tesoreria', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('firmas_paz_y_salvo', sa.Column('prueba', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('firmas_paz_y_salvo', sa.Column('inventario', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('firmas_paz_y_salvo', 'id_periodo',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('firmas_paz_y_salvo', 'id_estudiante',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('dir_firmas',
    sa.Column('id_dir_firma', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dir_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name='dir_firmas_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id_dir_firma', name='dir_firmas_pkey')
    )
    op.create_index('ix_dir_firmas_id_dir_firma', 'dir_firmas', ['id_dir_firma'], unique=False)
    op.drop_index(op.f('ix_detalle_firma_paz_y_salvo_id_detalle'), table_name='detalle_firma_paz_y_salvo')
    op.drop_table('detalle_firma_paz_y_salvo')
    op.drop_index(op.f('ix_responsable_firma_id_responsable'), table_name='responsable_firma')
    op.drop_table('responsable_firma')
    op.drop_index(op.f('ix_tipo_firma_id_tipo_firma'), table_name='tipo_firma')
    op.drop_table('tipo_firma')
    op.drop_index(op.f('ix_credenciales_login_id_credencial'), table_name='credenciales_login')
    op.drop_table('credenciales_login')
    # ### end Alembic commands ###
