"""Add importacion staging models

Revision ID: 521fd9c25d54
Revises: 87f7e0f17fbd
Create Date: 2026-05-30 01:23:32.878330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521fd9c25d54'
down_revision: Union[str, None] = '87f7e0f17fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejecuciones_bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_fin', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('registros_estudiantes', sa.Integer(), nullable=True),
    sa.Column('registros_docentes', sa.Integer(), nullable=True),
    sa.Column('errores', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_ejecucion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ejecuciones_bot_id'), 'ejecuciones_bot', ['id'], unique=False)
    op.create_table('errores_importacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejecucion_id', sa.Integer(), nullable=False),
    sa.Column('tipo_origen', sa.String(length=50), nullable=False),
    sa.Column('registro_referencia', sa.String(length=255), nullable=True),
    sa.Column('mensaje_error', sa.String(), nullable=False),
    sa.Column('fecha_error', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecuciones_bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_errores_importacion_id'), 'errores_importacion', ['id'], unique=False)
    op.create_table('staging_docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejecucion_id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('grado_titular', sa.String(length=100), nullable=True),
    sa.Column('curso_titular', sa.String(length=100), nullable=True),
    sa.Column('estado_validacion', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('fecha_carga', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecuciones_bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_docentes_documento'), 'staging_docentes', ['documento'], unique=False)
    op.create_index(op.f('ix_staging_docentes_id'), 'staging_docentes', ['id'], unique=False)
    op.create_table('staging_estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejecucion_id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('grado', sa.String(length=100), nullable=True),
    sa.Column('curso', sa.String(length=100), nullable=True),
    sa.Column('jornada', sa.String(length=100), nullable=True),
    sa.Column('estado_validacion', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('fecha_carga', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecuciones_bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_estudiantes_documento'), 'staging_estudiantes', ['documento'], unique=False)
    op.create_index(op.f('ix_staging_estudiantes_id'), 'staging_estudiantes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staging_estudiantes_id'), table_name='staging_estudiantes')
    op.drop_index(op.f('ix_staging_estudiantes_documento'), table_name='staging_estudiantes')
    op.drop_table('staging_estudiantes')
    op.drop_index(op.f('ix_staging_docentes_id'), table_name='staging_docentes')
    op.drop_index(op.f('ix_staging_docentes_documento'), table_name='staging_docentes')
    op.drop_table('staging_docentes')
    op.drop_index(op.f('ix_errores_importacion_id'), table_name='errores_importacion')
    op.drop_table('errores_importacion')
    op.drop_index(op.f('ix_ejecuciones_bot_id'), table_name='ejecuciones_bot')
    op.drop_table('ejecuciones_bot')
    # ### end Alembic commands ###
