"""grupo cambiado a str

Revision ID: 65e3ef7026ad
Revises: 278a5dd8c026
Create Date: 2026-05-31 23:46:46.996070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e3ef7026ad'
down_revision: Union[str, None] = '278a5dd8c026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salon', 'grupo',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salon', 'grupo',
               existing_type=sa.String(length=1),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
