"""migrar_logs_a_archivo

Revision ID: 6f5c72aa5694
Revises: 0616eb0b3d73
Create Date: 2026-06-03 23:05:40.148928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f5c72aa5694'
down_revision: Union[str, None] = '0616eb0b3d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_errores_importacion_id', table_name='errores_importacion')
    op.drop_table('errores_importacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errores_importacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ejecucion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_origen', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('registro_referencia', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mensaje_error', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fecha_error', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecuciones_bot.id'], name='errores_importacion_ejecucion_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='errores_importacion_pkey')
    )
    op.create_index('ix_errores_importacion_id', 'errores_importacion', ['id'], unique=False)
    # ### end Alembic commands ###
