"""renombrar_biblioteca_a_banda_en_tabla_firmas_paz_y_salvo

Revision ID: 8598fe908090
Revises: aef06b351c56
Create Date: 2026-05-17 20:45:51.016492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8598fe908090'
down_revision: Union[str, None] = 'aef06b351c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('firmas_paz_y_salvo', 'biblioteca', new_column_name='banda')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('firmas_paz_y_salvo', 'banda', new_column_name='biblioteca')
    # ### end Alembic commands ###
