"""remover_columna_codigo_mantener_id_instrumento

Revision ID: b39040be2245
Revises: 28cf8f7a9814
Create Date: 2026-06-04 18:00:04.265563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39040be2245'
down_revision: Union[str, None] = '28cf8f7a9814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventario_instrumento_codigo_key', 'inventario_instrumento', type_='unique')
    op.drop_column('inventario_instrumento', 'codigo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventario_instrumento', sa.Column('codigo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('inventario_instrumento_codigo_key', 'inventario_instrumento', ['codigo'])
    # ### end Alembic commands ###
