"""feat: modulo de importaciones unificado

Revision ID: ceb05f5c3b15
Revises: 8438a9245df3
Create Date: 2026-06-04 23:27:45.295007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ceb05f5c3b15'
down_revision: Union[str, None] = '8438a9245df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staging_docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejecucion_id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('grado_titular', sa.String(length=100), nullable=True),
    sa.Column('curso_titular', sa.String(length=100), nullable=True),
    sa.Column('estado_validacion', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('fecha_carga', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecuciones_bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_docentes_documento'), 'staging_docentes', ['documento'], unique=False)
    op.create_index(op.f('ix_staging_docentes_id'), 'staging_docentes', ['id'], unique=False)
    op.create_table('staging_estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejecucion_id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('grado', sa.String(length=100), nullable=True),
    sa.Column('curso', sa.String(length=100), nullable=True),
    sa.Column('jornada', sa.String(length=100), nullable=True),
    sa.Column('estado_validacion', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('fecha_carga', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_salon', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecuciones_bot.id'], ),
    sa.ForeignKeyConstraint(['id_salon'], ['salon.id_salon'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_estudiantes_documento'), 'staging_estudiantes', ['documento'], unique=False)
    op.create_index(op.f('ix_staging_estudiantes_id'), 'staging_estudiantes', ['id'], unique=False)
    op.drop_index('ix_errores_importacion_id', table_name='errores_importacion')
    op.drop_table('errores_importacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errores_importacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ejecucion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_origen', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('registro_referencia', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mensaje_error', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fecha_error', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ejecucion_id'], ['ejecuciones_bot.id'], name='errores_importacion_ejecucion_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='errores_importacion_pkey')
    )
    op.create_index('ix_errores_importacion_id', 'errores_importacion', ['id'], unique=False)
    op.drop_index(op.f('ix_staging_estudiantes_id'), table_name='staging_estudiantes')
    op.drop_index(op.f('ix_staging_estudiantes_documento'), table_name='staging_estudiantes')
    op.drop_table('staging_estudiantes')
    op.drop_index(op.f('ix_staging_docentes_id'), table_name='staging_docentes')
    op.drop_index(op.f('ix_staging_docentes_documento'), table_name='staging_docentes')
    op.drop_table('staging_docentes')
    # ### end Alembic commands ###
