"""empty message

Revision ID: e8f933781a2f
Revises: 8598fe908090
Create Date: 2026-05-24 16:14:10.417249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f933781a2f'
down_revision: Union[str, None] = '8598fe908090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_matricula',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_matricula', sa.Integer(), nullable=True),
    sa.Column('id_tipo', sa.Integer(), nullable=True),
    sa.Column('mes', sa.Enum('ENERO', 'FEBRERO', 'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMBRE', 'OCTUBRE', 'NOVIEMBRE', name='mesesenum'), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula.id_matricula'], ),
    sa.ForeignKeyConstraint(['id_tipo'], ['tipo_concepto.id_tipo'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_detalle_matricula_estado'), 'detalle_matricula', ['estado'], unique=False)
    op.create_index(op.f('ix_detalle_matricula_id_detalle'), 'detalle_matricula', ['id_detalle'], unique=False)
    op.add_column('tipo_prueba', sa.Column('descripcion', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipo_prueba', 'descripcion')
    op.drop_index(op.f('ix_detalle_matricula_id_detalle'), table_name='detalle_matricula')
    op.drop_index(op.f('ix_detalle_matricula_estado'), table_name='detalle_matricula')
    op.drop_table('detalle_matricula')
    # ### end Alembic commands ###
