"""add disponible to inventario_libro

Revision ID: ea8d29c24875
Revises: 22e732c2e318
Create Date: 2026-05-24 12:14:54.744709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8d29c24875'
down_revision: Union[str, None] = '22e732c2e318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventario_libro', sa.Column('disponible', sa.Boolean(), nullable=True))
    op.alter_column('inventario_libro', 'estado_fisico',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.add_column('prestamo_libro', sa.Column('estado', sa.Boolean(), nullable=True))
    op.drop_column('prestamo_libro', 'observacion_devolucion')
    op.alter_column('tipo_prueba', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tipo_prueba', 'descripcion',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('prestamo_libro', sa.Column('observacion_devolucion', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('prestamo_libro', 'estado')
    op.alter_column('inventario_libro', 'estado_fisico',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('inventario_libro', 'disponible')
    # ### end Alembic commands ###
