"""add_id_salon_to_staging_estudiantes

Revision ID: ec893dcc0fe4
Revises: 521fd9c25d54
Create Date: 2026-05-30 21:13:33.467067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec893dcc0fe4'
down_revision: Union[str, None] = '521fd9c25d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staging_estudiantes', sa.Column('id_salon', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'staging_estudiantes', 'salon', ['id_salon'], ['id_salon'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staging_estudiantes', type_='foreignkey')
    op.drop_column('staging_estudiantes', 'id_salon')
    # ### end Alembic commands ###
